### ISSUE TITLE
What does mu, tmu and velmu stand for?

### ISSUE THREAD

**Issue by anuroop18** [sotos82/SolarSystemSimulatorGame#3]
I was trying to understand how all the scripts work. But i couldn't understand what these terms mean Scales.cs:
**mu** in `public const float au2mu = 1000f;` 
**tmu** in `public const float tmu2y = 1 / y2tmu;`
**velmu** in `public const float velmu2kms = (mu2au * au2km) / (tmu2y * y2sec);`
If you could just provide me meaning of these terms, it would me really helpful.
Thanks

**Comment by sotos82** [comment]
Hello,
those are parameters to convert the units from mu (model or in game units) to real units
e.g. au (= astronomical unit) equals 1000 model unitsvelmu2kms => velocity model unit to km/sy2sec is year to seconds
    Στις Τετάρτη, 15 Ιανουαρίου 2020, 08:13:49 μ.μ. EET, ο χρήστης Anuroop Singh <notifications@github.com> έγραψε:  
 
 
I was trying to understand how all the scripts work. But i couldn't understand what these terms mean Scales.cs:
mu in public const float au2mu = 1000f;
tmu in public const float tmu2y = 1 / y2tmu;
velmu in public const float velmu2kms = (mu2au * au2km) / (tmu2y * y2sec);
If you could just provide me meaning of these terms, it would me really helpful.
